server:
  port: 8088

#logging:
#  level:
#    org.springframework: debug

spring:
  messages:
    basename: messages
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  output:
    ansi:
      enabled: always

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

#  security:
#    user:
#      name: username
#      password: passw0rd

management:
  endpoints:
    web:
      exposure:
        include: '*'
